name: Linux

on: push

jobs:

  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0'

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2

      - name: Build Snap Image
        run: sudo snapcraft --destructive-mode
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Snap
          path: avarex*.snap
